package com.youdash.model;

public enum OrderStatus {
    CREATED,
    SEARCHING_RIDER,
    RIDER_ACCEPTED,
    PAYMENT_PENDING,
    CONFIRMED,
    PICKED_UP,
    AT_ORIGIN_HUB,
    DEPARTED_ORIGIN_HUB,
    IN_TRANSIT,
    AT_DESTINATION_HUB,
    SORTED_AT_DESTINATION,
    OUT_FOR_DELIVERY,
    READY_FOR_PICKUP,
    DELIVERED,
    FAILED_DELIVERY,
    CANCELLED,
    RETURNED,
    EXPIRED,
    FAILED
}
