spring.application.name=parcel

# ===============================
# SERVER CONFIG
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIG (HOSTINGER)
# ===============================
spring.datasource.url=${DB_URL:jdbc:mysql://srv789.hstgr.io:3306/u820447105_youdbparcel}
spring.datasource.username=${DB_USERNAME:u820447105_youdbparcel}
spring.datasource.password=${DB_PASSWORD:Youdash@1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# HIKARI CONNECTION POOL SETTINGS
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# RAZORPAY CONFIG
# ===============================
razorpay.key_id=rzp_test_SaaE96s2iCG8a1
razorpay.key_secret=lGI2eja2i4V1AurdSG1zgSPl

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=MySecretKeyForJwtAuthenticationParcelDeliveryApp2026
jwt.expiration=86400000
